version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 051826729213.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t parekh-final-test-api .
      - docker tag parekh-final-test-api:latest 051826729213.dkr.ecr.us-east-1.amazonaws.com/parekh-final-test-api:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 051826729213.dkr.ecr.us-east-1.amazonaws.com/parekh-final-test-api:latest
      - echo Generating imagedefinitions.json...
      - printf '[{"name":"parekh-app","imageUri":"051826729213.dkr.ecr.us-east-1.amazonaws.com/parekh-final-test-api:latest"}]' > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json